### ISSUE TITLE
eos_cli_config_gen documentation fix

### ISSUE THREAD

**Issue by emmanuel-oginni** [aristanetworks/ansible-avd#673] opened 2021-02-01 22:54 UTC
## Issue Type
- [x] Documentation Issue Report

## Summary

The documentation for AVD configuration needs to be corrected to properly configure timezone for Arista devices through the AVD.
The documentation https://github.com/aristanetworks/ansible-avd/tree/devel/ansible_collections/arista/avd/roles/eos_cli_config_gen#clock-timezone specified to use the clock definition as given below, which did not work as expected:
clock:
    timezone: < timezone >

No timezone definition was included in our Arista configuration through the AVD when this instruction was followed.

A review of the AVD collection showed that the definition is overridden by the use of clock definition in arista\avd\roles\eos_l3ls_evpn\templates\evpn-fabric-l3leaf-yml.j2 and arista\avd\roles\eos_l3ls_evpn\templates\base\clock-timezone.j2

The current work around is to define timezone instead of clock.

## Component Name
eos_cli_config_gen

## Steps to reproduce
Not applicable

### Actual results
Not applicable

**Comment by titom73** [comment] 2021-02-02 08:06
Hello @emmanuel-oginni 

Could you share your variable settings ? Indeed, I am using the following configuration and I have correct CLI configuration output

```yaml
clock:
  timezone: Europe/Paris
```

and CLI is:

```
!
clock timezone Europe/Paris
!
```

Kind Regards,

**Comment by emmanuel-oginni** [comment] 2021-02-03 03:10
[avd.zip](https://github.com/aristanetworks/ansible-avd/files/5915797/avd.zip)
I attached a zipped copy of avd used for the testing. The command used for the testing is : 
ansible-playbook avd/playbooks/DMO-fabric-deploy-cvp.yml -i avd/inventories/DMO/inventory.yml  --tag build

My investigation is that the template arista\avd\roles\eos_l3ls_evpn\templates\evpn-fabric-l3leaf-yml.j2 create an empty clock dictionary if timezone is not defined from lines:
{# clock timezone #}
### Clock Timezone ###
clock:
{% include 'base/clock-timezone.j2' %}

from arista\avd\roles\eos_l3ls_evpn\templates\base\clock-timezone.j2  
{% if timezone is defined %}
  timezone: {{ timezone }}
{% endif %}

The result is that clock definition on the fabric is not effective.

**Comment by titom73** [comment] 2021-02-03 07:46
hello @emmanuel-oginni 

I will try to replicate your issue with the information you shared.

Updated information:

- Impacted Role: `arista.avd.eos_l3ls_evpn`
- Impacted files:
  - [Device Template](https://github.com/aristanetworks/ansible-avd/blob/9211995e0ac8c3f7eaf616840c6d2919d0be89de/ansible_collections/arista/avd/roles/eos_l3ls_evpn/templates/evpn-fabric-spine-yml.j2#L115)
  - [Timezone template](https://github.com/aristanetworks/ansible-avd/blob/devel/ansible_collections/arista/avd/roles/eos_l3ls_evpn/templates/base/clock-timezone.j2)

**Comment by titom73** [comment] 2021-02-03 08:17
After testing for confirmation, here is a step by step analysis:

__Fabric configuration__

Based on [eos_l3ls_evpn documentation](https://www.avd.sh/en/latest/roles/eos_l3ls_evpn/), timezone should be configured as below:

```yaml
# Clock timezone | Optional
timezone: Europe/Paris
```

> It is directly at the top of YAML structure, i.e. not under another keyword.

__L3LS_EVPN Output / cli_config_gen input__

l3ls_evpn generate a structured configuration in YAML based on eos_cli_config_gen data model under intended/structured_configs/<device_hostname>.yml

```yaml
clock:
  timezone: Europe/Paris
```

__EOS Configuration__

As a final state, eos_cli_config_gen will render configuration in  an EOS manner

```
!
clock timezone Europe/Paris
!
```

**Comment by carlbuchmann** [comment] 2021-03-20 20:13
Closing, as we are not able to reproduce issue.

**Closed as completed by carlbuchmann** 2021-03-20 20:13 UTC
Labels: type: question, role: eos_l3ls_evpn
