### ISSUE TITLE
Feat(eos_designs): Add router general to eos-designs

### ISSUE THREAD

**Issue by tgodaA** [aristanetworks/ansible-avd#2607] opened 2023-03-08 11:50 UTC
### Enhancement summary

Use the feature `use_general_router_id: <bool>` to not configure router-id under every router_bgp.vrf. This allows us to use generic router-id for all vrfs defined under the router-general. 

### Which component of AVD is impacted

eos_designs

### Use case example

To enable the router_id defined at one place --> router-general.

### Describe the solution you would like

`use_general_router_id: <bool>` should enable the router general configuration and not print all of the router-id config under router-bgp VRFs.

### Contributing Guide

- [X] I agree to follow this project's Code of Conduct

**Comment by ClausHolbechArista** [comment] 2024-01-10 13:54
Duplicate of #1245

**Closed as completed by ClausHolbechArista** 2024-01-10 13:54 UTC
Labels: type: enhancement
