### ISSUE TITLE
eos_l3ls_evpn: AnsibleParserError: 'NoneType' object has no attribute 'line' if peer device is not in topology

### ISSUE THREAD

**Issue by kmueller68** [aristanetworks/ansible-avd#700] opened 2021-02-10 07:43 UTC
## Issue Type

- [x] Bug Report

## Summary

eos_l3ls_evpn gives me an error during generation of the fabric documentation, when the "peer" device of an ethernet interface is not in the current topology.

I have to add a mlag peer link connection to a neighbor leaf switch in another fabric topology.
Therfore I set the "peer: <remote switch name> unter the ethernet interface.

```
TASK [eos_l3ls_evpn : Generate EVPN fabric documentation in Markdown Format.] **************************************************************************************************
fatal: [spine-1a7-01.DC.MU -> localhost]: FAILED! => {"changed": false, "msg": "AnsibleParserError: 'NoneType' object has no attribute 'line'"}
```

## Component Name
eos_l3ls_evpn

## Steps to reproduce

```yaml
   Ethernet50/1:
     peer: leaf-remote-topo
     peer_interface: Ethernet50/1
     peer_type: mlag_peer
     description: MLAG_PEER_leaf-remote-topo_Ethernet50/1
     type: switched
     shutdown: false
```

### Expected results

documentation\fabric\D1_FABRIC-topology.csv

``` 
l3leaf,leaf-local-topo,Ethernet50/1,mlag_peer,leaf-remote-topo,Ethernet50/1
```

### Actual results

```shell
TASK [eos_l3ls_evpn : Generate EVPN fabric documentation in Markdown Format.] **************************************************************************************************
fatal: [spine-local-01 -> localhost]: FAILED! => {"changed": false, "msg": "AnsibleParserError: 'NoneType' object has no attribute 'line'"}
```

**Comment by kmueller68** [comment] 2021-02-10 08:18
Additional comment:
host_vars/leaf-local.topo.yml

```yaml
custom_structured_configuration_ethernet_interfaces:
   Ethernet50/1:
     peer: leaf-remote-topo
     peer_interface: Ethernet50/1
     peer_type: mlag_peer
     description: MLAG_PEER_leaf-remote-topo_Ethernet50/1
     type: switched
     shutdown: false
```
I have two different dev envionments. Its is working in one but not in the other.
But I have not yet been able to locate the issue.

**Comment by titom73** [comment] 2021-02-10 08:21
Hi @kmueller68 

Are you using the same version of the collection for your 2 dev environments? Could you share commit ID you are using?

Indeed, we had a PR related to fabric documentation recently and it will help us to look for root cause and if it is still in the code.

**Comment by kmueller68** [comment] 2021-02-10 08:43
Hi @titom73 

**working env**:
devel 
commit c9bac5a324f8d033bf4b0c3dd75e05c47adfc6d4 (HEAD -> devel, origin/devel, origin/HEAD)
Merge: f170ef76 ac271b2b
Author: TiTom73 <tgrimonet@arista.com>
Date:   Thu Feb 4 08:44:56 2021 +0100

    Merge pull request #660 from titom73/issues/506

**non-working env:**
devel
commit bebe5dab6c90d3c3928b45678d21fd15ac4d1828 (HEAD -> devel, origin/devel)
Merge: c9bac5a3 c3f343f8
Author: Carl Buchmann <carl.buchmann@arista.com>
Date:   Mon Feb 8 11:18:31 2021 -0500

    Merge pull request #691 from titom73/ci/mkdocs-issue-671-v2

    Move cURL validation in mkdocs container + CI simplification

commit c3f343f886cff6d5aaffa37faa99901e676c206a
Author: TiTom73 <thomas.grimonet@gmail.com>
Date:   Sun Feb 7 10:40:55 2021 +0100

    Fix missing exclusion check from previous commit

commit 3bc6aa19305440a56c6963094e4dee8a5a858709
Author: Thomas Grimonet <tgrimonet@arista.com>
Date:   Sat Feb 6 19:26:44 2021 +0100

    CI workflow update

commit e5c9367cb41b21867bc670740c623431ffe15909
Merge: 60a0185c c9bac5a3
Author: TiTom73 <tgrimonet@arista.com>
Date:   Sat Feb 6 19:14:34 2021 +0100

    Merge branch 'devel' into ci/mkdocs-issue-671-v2

commit 60a0185c196fd2afa87e02d0a0e8a22f372cf887
Author: Thomas Grimonet <tgrimonet@arista.com>
Date:   Sat Feb 6 19:10:08 2021 +0100

    Move curl validation in mkdocs container + CI simplification

commit c9bac5a324f8d033bf4b0c3dd75e05c47adfc6d4 (origin/refactor/eos-cli-config-gen)
Merge: f170ef76 ac271b2b
Author: TiTom73 <tgrimonet@arista.com>
Date:   Thu Feb 4 08:44:56 2021 +0100

    Merge pull request #660 from titom73/issues/506

**Comment by titom73** [comment] 2021-02-10 12:27
Hi @kmueller68 

I have tested following configuration at both commits and was able to get documentation generated with no error

```yaml
# inventories/inetsix-eapi/host_vars/EAPI-BL01A/issue-700.yml
custom_structured_configuration_ethernet_interfaces:
   Ethernet50/1:
     peer: leaf-remote-topo
     peer_interface: Ethernet50/1
     peer_type: mlag_peer
     description: MLAG_PEER_leaf-remote-topo_Ethernet50/1
     type: switched
     shutdown: false
```

Result is the same for both bebe5da & c9bac5a :

```markdown
| Type | Node | Node Interface | Peer Type | Peer Node | Peer Interface |
| ---- | ---- | -------------- | --------- | ----------| -------------- |
| l2leaf | EAPI-AGG01 | Ethernet1 | l3leaf | EAPI-LEAF1A | Ethernet5 |
| l2leaf | EAPI-AGG01 | Ethernet2 | l3leaf | EAPI-LEAF1B | Ethernet5 |
| l2leaf | EAPI-AGG02 | Ethernet1 | l3leaf | EAPI-LEAF2A | Ethernet5 |
| l2leaf | EAPI-AGG02 | Ethernet2 | l3leaf | EAPI-LEAF2B | Ethernet5 |
| l3leaf | EAPI-BL01A | Ethernet1 | spine | EAPI-SPINE1 | Ethernet5 |
| l3leaf | EAPI-BL01A | Ethernet2 | spine | EAPI-SPINE2 | Ethernet5 |
| l3leaf | EAPI-BL01A | Ethernet3 | mlag_peer | EAPI-BL01B | Ethernet3 |
| l3leaf | EAPI-BL01A | Ethernet4 | mlag_peer | EAPI-BL01B | Ethernet4 |
| l3leaf | EAPI-BL01A | Ethernet50/1 | mlag_peer | leaf-remote-topo | Ethernet50/1 |
```

Besides that, `git diff` does not return change related to fabric documentation and looking for `line` variable return only same result for both commits and all related to a `csv_line`:

```bash
egrep -R line ansible_collections/arista/avd/roles/eos_l3ls_evpn/templates/*
ansible_collections/arista/avd/roles/eos_l3ls_evpn/templates/documentation/fabric-p2p-links.j2:{%                         set csv_line = [] %}
ansible_collections/arista/avd/roles/eos_l3ls_evpn/templates/documentation/fabric-p2p-links.j2:{%                         do csv_line.append(hostvars[node].type) %}
ansible_collections/arista/avd/roles/eos_l3ls_evpn/templates/documentation/fabric-p2p-links.j2:{%                         do csv_line.append(node) %}
ansible_collections/arista/avd/roles/eos_l3ls_evpn/templates/documentation/fabric-p2p-links.j2:{%                         do csv_line.append(ethernet_interface) %}
ansible_collections/arista/avd/roles/eos_l3ls_evpn/templates/documentation/fabric-p2p-links.j2:{%                         do csv_line.append(hostvars[node].ethernet_interfaces[ethernet_interface].ip_address | arista.avd.default("")) %}
ansible_collections/arista/avd/roles/eos_l3ls_evpn/templates/documentation/fabric-p2p-links.j2:{%                         do csv_line.append(hostvars[node].ethernet_interfaces[ethernet_interface].peer_type) %}
ansible_collections/arista/avd/roles/eos_l3ls_evpn/templates/documentation/fabric-p2p-links.j2:{%                         do csv_line.append(peer) %}
ansible_collections/arista/avd/roles/eos_l3ls_evpn/templates/documentation/fabric-p2p-links.j2:{%                         do csv_line.append(peer_interface) %}
ansible_collections/arista/avd/roles/eos_l3ls_evpn/templates/documentation/fabric-p2p-links.j2:{%                         do csv_line.append(peer_ip_address) %}
ansible_collections/arista/avd/roles/eos_l3ls_evpn/templates/documentation/fabric-p2p-links.j2:{{ csv_line | join(",") }}
ansible_collections/arista/avd/roles/eos_l3ls_evpn/templates/documentation/fabric-topology.j2:{%             set csv_line = [] %}
ansible_collections/arista/avd/roles/eos_l3ls_evpn/templates/documentation/fabric-topology.j2:{%             do csv_line.append(hostvars[node].type) %}
ansible_collections/arista/avd/roles/eos_l3ls_evpn/templates/documentation/fabric-topology.j2:{%             do csv_line.append(node) %}
ansible_collections/arista/avd/roles/eos_l3ls_evpn/templates/documentation/fabric-topology.j2:{%             do csv_line.append(ethernet_interface) %}
ansible_collections/arista/avd/roles/eos_l3ls_evpn/templates/documentation/fabric-topology.j2:{%             do csv_line.append(hostvars[node].ethernet_interfaces[ethernet_interface].peer_type | arista.avd.default("")) %}
ansible_collections/arista/avd/roles/eos_l3ls_evpn/templates/documentation/fabric-topology.j2:{%             do csv_line.append(hostvars[node].ethernet_interfaces[ethernet_interface].peer | arista.avd.default("")) %}
ansible_collections/arista/avd/roles/eos_l3ls_evpn/templates/documentation/fabric-topology.j2:{%             do csv_line.append(hostvars[node].ethernet_interfaces[ethernet_interface].peer_interface | arista.avd.default("")) %}
ansible_collections/arista/avd/roles/eos_l3ls_evpn/templates/documentation/fabric-topology.j2:{{ csv_line | join(",") }}
ansible_collections/arista/avd/roles/eos_l3ls_evpn/templates/evpn-fabric-l3leaf-yml.j2:{# intentional blank line #}
ansible_collections/arista/avd/roles/eos_l3ls_evpn/templates/evpn-fabric-overlay-controller-yml.j2:{# intentional blank line #}
```

Still working to reproduce this behavior

**Comment by kmueller68** [comment] 2021-02-10 13:29
Hi @titom73

Thank you for testing. Could I help with any logs or debugs from my environment?

**Comment by titom73** [comment] 2021-02-10 15:54
Hello @kmueller68 

Could you share the output of playbook execution in verbose mode in your non-working environment?

In addition, could you also share result of `egrep -R line ansible_collections/arista/avd/roles/eos_l3ls_evpn/templates/*`

Thanks

**Comment by kmueller68** [comment] 2021-02-10 16:28
Hi @titom73 

verbose showed the following error which lead me to the solution.

TASK [eos_l3ls_evpn : Generate EVPN fabric documentation in Markdown Format.] **************************************************************************************************
task path: /arista/DevNetOps/roles/ansible-avd/ansible_collections/arista/avd/roles/eos_l3ls_evpn/tasks/main.yml:25
<localhost> ESTABLISH LOCAL CONNECTION FOR USER: ans_cvp
<localhost> EXEC /bin/sh -c 'echo ~ans_cvp && sleep 0'
<localhost> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /home/ans_cvp/.ansible/tmp/ansible-tmp-1612973664.6274757-93256323275873 `" && echo ansible-tmp-1612973664.6274757-93256323275873="` echo /home/ans_cvp/.ansible/tmp/ansible-tmp-1612973664.6274757-93256323275873 `" ) && sleep 0'
<localhost> EXEC /bin/sh -c 'rm -f -r /home/ans_cvp/.ansible/tmp/ansible-tmp-1612973664.6274757-93256323275873/ > /dev/null 2>&1 && sleep 0'
fatal: [spine-1a7-01.DC.MU -> localhost]: FAILED! => {
    "changed": false,
    "msg": "AnsibleParserError: Syntax Error while loading YAML.\n  did not find expected <document start>\n\nThe error appears to be in '/arista/DevNetOps/host_vars/leaf-11f2-02.DC.MU.yml': line 7, column 1, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n# MLAG WANT/TK leafs pair\ncustom_structured_configuration_leaf_mlag: true\n^ here\n"
}

NO MORE HOSTS LEFT

There have been some inconsistent values between the two host files of the corresponding MLAG switches.
I could fix it now and it is working correct now.

Your code is working well.

Thank you super very much for your support on this.


l3leaf,leaf-11f2-01.DC.MU,Ethernet50/1,mlag_peer,leaf-11f2-02.DC.MU,Ethernet50/1
l3leaf,leaf-11f2-01.DC.MU,Ethernet51/1,spine,spine-1a7-01.DC.MU,Ethernet1/11/1
l3leaf,leaf-11f2-01.DC.MU,Ethernet52/1,spine,spine-1a7-02.DC.MU,Ethernet1/11/1
l3leaf,leaf-11f2-01.DC.MU,Ethernet54/1,mlag_peer,leaf-11f2-02.DC.MU,Ethernet54/1

**Comment by titom73** [comment] 2021-02-10 16:30
Cool if it is fixed now.

Happy to be in touch anytime you need

**Closed as completed** 2021-02-10 16:30 UTC
Labels: role: eos_l3ls_evpn, state: invalid
