### ISSUE TITLE
Stun server profile name created by AVD is invalid (Contains `/` char)

### ISSUE THREAD

**Issue by rohiniprem** [aristanetworks/ansible-avd#3987] opened 2024-05-13 12:36 UTC
### Issue Summary

When creating stun server profile via AVD, when there are multiple stun interfaces, AVD creates server-profiles including the interface name. But the interface name contains `/` character which is not a valid input.

For eg. - 
ind359.05:32:35(config)#stun
ind359.05:32:37(config-stun)#client
ind359.05:32:38(config-stun-client)#server-profile Internet-astoria-blr-pf-ind468-Ethernet1/1
% Invalid input
ind359.05:33:31(config-stun-client)#

Due to this, we are getting this error in cv-staging - 

stun server-profile Internet-astoria-blr-pf-ind468-Ethernet1/1 Internet-astoria-blr-pf-ind468-Ethernet1/5 Internet-astoria-pf1-Ethernet1 % Invalid input (at token 2: 'Internet-astoria-blr-pf-ind468-Ethernet1/1')

### Which component(s) of AVD impacted

eos_cli_config_gen, arista.avd.configlet_build_config

### How do you run AVD ?

Ansible CLI (with virtual-env or native python)

### Contributing Guide

- [X] I agree to follow this project's Code of Conduct

**Comment by gmuloc** [comment] 2024-05-13 12:41
Duplicate of https://github.com/aristanetworks/avd/issues/3940 - fixed in devel via https://github.com/aristanetworks/avd/pull/3949

**Closed as completed by gmuloc** 2024-05-13 12:41 UTC
Labels: type: bug
