### ISSUE TITLE
Add Storm Control to Port Channel Interfaces Cli config gen

### ISSUE THREAD

**Issue by ernestoherrerab** [aristanetworks/ansible-avd#1066] opened 2021-06-29 11:44 UTC
**Issue Type**

- [ ] Template enhancement
- [X ] Role enhancement
- [ ] Documentation enhancement (avd.sh)

**Is your feature request related to a problem? Please describe.**
Sort of, we are migrating to EVPN/VXLAN and some of our existing Port Channels are using storm control and this would facilitate their migration.

It is easier to implement commands on the port channel directly instead of on individual interfaces (which might not even be supported)

There is no structured data in the port_channel_interfaces  on the cli config gen

**Describe the solution you'd like**

Add the same keys for storm control as the one available for ethernet_interfaces

Add the below to port_channel_interfaces

    storm_control:
      all:
        level: < Configure maximum storm-control level >
        unit: < percent* | pps (optional and is hardware dependant - default is percent)>
      broadcast:
        level: < Configure maximum storm-control level >
        unit: < percent* | pps (optional and is hardware dependant - default is percent)>
      multicast:
        level: < Configure maximum storm-control level >
        unit: < percent* | pps (optional and is hardware dependant - default is percent) >
      unknown_unicast:
        level: < Configure maximum storm-control level >
        unit: < percent* | pps (optional and is hardware dependant - default is percent)>

**Describe alternatives you've considered**

**Additional context**

**Comment by ankudinov** [comment] 2021-07-05 17:06
duplicate of #154

**Comment by ClausHolbechArista** [comment] 2021-07-09 19:16
So this turned out to be missing documentation. Lost somewhere since #154 got implemented.

**Closed as completed** 2021-07-10 12:53 UTC
Labels: type: enhancement, role: eos_cli_config_gen
