### ISSUE TITLE
Add IPv6 support for SVI definition under tenants

### ISSUE THREAD

**Issue by titom73** [aristanetworks/ansible-avd#1202] opened 2021-09-17 12:14 UTC
### Enhancement summary

Today SVI definition only supports IPv4 definition but would be important to supports IPv6 for some designs.

### Which component of AVD is impacted

eos_designs

### Use case example

Need to support IPv6 networks.

### Describe the solution you would like

At least the following configuration should be supported

```
interface Vlan123
     description NDN-Testnet
     ip address 109.105.123.3/25
     ip virtual-router address 109.105.123.1
     ipv6 address 2001:948:123:4::3/64
     ipv6 virtual-router address 2001:948:123:4::1
```

### Describe alternatives you have considered

Use of `structured_config` under SVI but not optimal for something to add to every single SVI.

```
# Custom structured config added under vlan_interfaces.<interface> for eos_cli_config_gen
structured_config: < dictionary >
```

### Additional context

Customer's project requirements

### Contributing Guide

- [X] I agree to follow this project's Code of Conduct

**Comment by ClausHolbechArista** [comment] 2021-10-29 10:52
Duplicate of #1106

**Closed as completed by ClausHolbechArista** 2021-10-29 10:52 UTC
Labels: type: enhancement
